server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:

        # TEAM SERVICE (via Eureka)
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie

        # PLAYER SERVICE
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie

        # MATCH SERVICE
        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/matches/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie

        # SCORING SERVICE
        - id: scoring-service
          uri: lb://scoring-service
          predicates:
            - Path=/api/scoring/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie

        # STATS SERVICE
        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # in Railway env: EUREKA_URL=https://cricket-scoring-system-production.up.railway.app/eureka/
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true
    hostname: gateway-production-bd9c.up.railway.app
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
