server:
  port: ${PORT:8080}     # Render uses dynamic PORT

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
		corsConfigurations:
		          '[/**]':
		            allowedOrigins: "*"
		            allowedMethods: "*"
		            allowedHeaders: "*"
            		allowCredentials: true

      routes:
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**

        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/players/**

        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/matches/**

        - id: scoring-service
          uri: lb://scoring-service
          predicates:
            - Path=/api/scoring/**

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/stats/**

eureka:
  client:
    service-url:
      # IMPORTANT: Replace <DISCOVERY_URL> AFTER deployment
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
