server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:

      discovery:
        locator:
          enabled: false

      routes:

        - id: team-service
          uri: https://team-production-35c9.up.railway.app
          predicates:
            - Path=/teams/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: player-service
          uri: https://player-production-2472.up.railway.app
          predicates:
            - Path=/players/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: match-service
          uri: https://match-production-5555.up.railway.app
          predicates:
            - Path=/matches/**
          filters:
            - RemoveRequestHeader=Cookie   # âœ… KEEP EXACTLY THIS

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true
